### ISSUE TITLE
Players are able to spam flashbangs on breakfloor

### ISSUE THREAD

**Issue by kleinpa** [lanofdoom/counterstrikesource-map-settings#1]

**Comment by BradleyMarie** [comment]
I've been working around this issue to date by setting the buy time to 15 seconds. I figured 15 seconds of flashbang spam isn't the end of the world.

That said, it's also trivial to just disable or limit the purchasing of flashbangs on breakfloor. We could also probably adjust the price on a per-level basis.

If we're not happy with the time-based approach, I think the best thing to do is apply per-level limits on grenade purchases.

**Comment by kleinpa** [comment]
Can we just `mp_buytime 0` and give everyone a M249 plus grenades?

**Comment by BradleyMarie** [comment]
I actually like the weapon variety. I think we should try a per-round grenade limit and see how that works out.

**Comment by BradleyMarie** [comment]
Fixed in v1.6.0
